# This is a basic workflow to help you get started with Actions

name: PlatformIO CI

on:
    push:
        branches: [ 2.0.6.1-ender5 ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1
        - name: Set up Python
          uses: actions/setup-python@v1
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install platformio
        - name: Run PlatformIO
          run: platformio run
